### ISSUE TITLE
Endpoint issues with SwissID login

### ISSUE THREAD

**Issue by abertschi** [abertschi/postcard_creator_wrapper#20]
postcard_creator_wrapper currently malfunctioning.

```
postcards_folder (INFO): checking for valid accounts
22095root (INFO): using legacy username password authentication
22096root (INFO): legacy username password authentication failed
22097root (ERROR): Username/password authentication failed. Are your credentials valid?.
22098root (INFO): using swissid username password authentication
22099Traceback (most recent call last):
22100  File "/home/bean/projects/postcards/venv/bin/postcards-folder", line 11, in <module>
22101    load_entry_point('postcards', 'console_scripts', 'postcards-folder')()
22102  File "/home/bean/projects/postcards/postcards.git/postcards/plugin_folder/postcards_folder.py", line 134\
     , in main
22103    PostcardsFolder().main(sys.argv[1:])
22104  File "/home/bean/projects/postcards/postcards.git/postcards/postcards.py", line 52, in main
22105    self.do_command_send(args)
22106  File "/home/bean/projects/postcards/postcards.git/postcards/postcards.py", line 102, in do_command_send
22107    stop_on_first_valid=not args.all_accounts)
22108  File "/home/bean/projects/postcards/postcards.git/postcards/postcards.py", line 175, in _create_pcc_wrap\
     pers
22109    if token.has_valid_credentials(account.get('username'), account.get('password')):
22110  File "/home/bean/projects/postcards/venv/lib/python3.6/site-packages/postcard_creator/token.py", line 72\
     , in has_valid_credentials
22111    self.fetch_token(username, password, method=method)
22112  File "/home/bean/projects/postcards/venv/lib/python3.6/site-packages/postcard_creator/token.py", line 10\
     4, in fetch_token
22113    saml_response = self._get_swissid_saml_response(session, username, password)
22114  File "/home/bean/projects/postcards/venv/lib/python3.6/site-packages/postcard_creator/token.py", line 19\
     9, in _get_swissid_saml_response
22115    goto_param = re.search(r'&goto=(.*?)$', step1_goto_url.url).group(1)
22116AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by abertschi** [comment]
cli client: https://github.com/abertschi/postcards/issues/46

**Comment by abertschi** [comment]
Status: https://github.com/abertschi/postcard_creator_wrapper/pull/21#issuecomment-739562527

**Comment by wp99cp** [comment]
If found a solution: See comment on #21
