### ISSUE TITLE
Endpoint Issue with swissid authentication

### ISSUE THREAD

**Issue by abertschi** [abertschi/postcard_creator_wrapper#29]
```
postcard_creator (INFO): swissid username password authentication failed
postcard_creator (INFO): 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/bean/projects/postcards/venv/bin/postcards-pexels", line 11, in <module>
    load_entry_point('postcards', 'console_scripts', 'postcards-pexels')()
  File "/home/bean/projects/postcards/postcards.git/postcards/plugin_pexels/postcards_pexels.py", line 24, in main
    PostcardsPexel().main(sys.argv[1:])
  File "/home/bean/projects/postcards/postcards.git/postcards/postcards.py", line 55, in main
    self.do_command_send(args)
  File "/home/bean/projects/postcards/postcards.git/postcards/postcards.py", line 105, in do_command_send
    stop_on_first_valid=not args.all_accounts)
  File "/home/bean/projects/postcards/postcards.git/postcards/postcards.py", line 178, in _create_pcc_wrappers
    if token.has_valid_credentials(account.get('username'), account.get('password')):
  File "/home/bean/projects/postcards/venv/lib/python3.6/site-packages/postcard_creator/token.py", line 84, in has_valid_credentials
    self.fetch_token(username, password, method=method)
  File "/home/bean/projects/postcards/venv/lib/python3.6/site-packages/postcard_creator/token.py", line 129, in fetch_token
    raise e
  File "/home/bean/projects/postcards/venv/lib/python3.6/site-packages/postcard_creator/token.py", line 123, in fetch_token
    access_token = self._get_access_token_swissid(session, username, password)
  File "/home/bean/projects/postcards/venv/lib/python3.6/site-packages/postcard_creator/token.py", line 236, in _get_access_token_swissid
    goto_param = re.search(r'goto=(.*?)$', step1_goto_url.url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by abertschi** [comment]
was this fixed with #27 ?

**Comment by wp99cp** [comment]
Can you elaborate a little bit on the problem, what are you trying to do? Maybe with a code snippet.
I quickly tried it out, sending a postcard with swiss-id as the login method works fine for me.

**Comment by abertschi** [comment]
Yes, just verified it. It was fixed already. I need to make a new release. Thanks for the response :)

**Comment by abertschi** [comment]
#30
