### ISSUE TITLE
Reference to pytest-runner in setup.py

### ISSUE THREAD

**Issue by abertschi** [abertschi/postcard_creator_wrapper#32]
```
pip install postcard-creator

Collecting postcard-creator
  Using cached https://files.pythonhosted.org/packages/b7/fa/d7261b4be791bbb9930492372b9d8b78896adb9048778da2f93a5b9ff51f/postcard_creator-2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-88znyog3/postcard-creator/setup.py", line 38, in <module>
        test_suite = 'tests',
      File "/home/bean/.pyenv/versions/3.6.1/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/bean/projects/postcards/source/venv/lib/python3.6/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/bean/projects/postcards/source/venv/lib/python3.6/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/bean/projects/postcards/source/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 850, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/bean/projects/postcards/source/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1122, in best_match
        return self.obtain(req, installer)
      File "/home/bean/projects/postcards/source/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1134, in obtain
        return installer(requirement)
      File "/home/bean/projects/postcards/source/venv/lib/python3.6/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/bean/projects/postcards/source/venv/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')
```

Workaround until new version released:

pip install pytest-runner

then try again:
pip install postcard-creator

Same applies for pip package: postcards

**Comment by abertschi** [comment]
#34
